CREATE TABLE  "DEPOSIT" 
   (	"DEPOSIT_ID" NUMBER NOT NULL ENABLE, 
	"DEPOSIT_NAME" VARCHAR2(25), 
	 CONSTRAINT "DEPOSIT_PK" PRIMARY KEY ("DEPOSIT_ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PHARMACY" 
   (	"PHARMACY_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"PHARMACY_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PHARMACY_DEPOSIT" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "PHARMACY_PK" PRIMARY KEY ("PHARMACY_ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ORDERS" 
   (	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"PHARMACY_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"PRODUCT_QUANTITY" NUMBER NOT NULL ENABLE, 
	"PRODUCT_CATEGORY" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCT_PRICE" NUMBER(5,2) NOT NULL ENABLE, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCT_CATEGORY_CK" CHECK ("PRODUCT_CATEGORY" in ('analgezice','anabolizante', 'vitamine','antibiotice','siropuri')) ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "ORDERS" ADD CONSTRAINT "ORDERS_FK" FOREIGN KEY ("PHARMACY_ID")
	  REFERENCES  "PHARMACY" ("PHARMACY_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "PHARMACY" ADD CONSTRAINT "PHARMACY_FK" FOREIGN KEY ("PHARMACY_DEPOSIT")
	  REFERENCES  "DEPOSIT" ("DEPOSIT_ID") ON DELETE CASCADE ENABLE
/
